<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="Tests" Id="{27552b28-ca6c-444c-9236-5c59da3f3bc4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Tests
VAR
    list_Person_Test : List_Person_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>